platform :ios

pod 'AFNetworking', '1.0RC1'
pod 'SDWebImage',   '2.6'
pod 'FormatterKit', '1.0.1'
pod 'BlockAlertsAnd-ActionSheets', '1.0.0'
pod 'MBProgressHUD', '0.5'
pod 'SFHFKeychainUtils', '0.0.1'
pod 'Reachability', '3.0.0'
